INSERT INTO ha_module (`name`, `class`, `tier`, `description`, `damage`, `frequency`, `damage_range`, `price`, `sell_price`) VALUES ('Bitcoin Miner', 'money', 1, 'Default Bitcoin Miner', 0, 10, 0, 1000, 0);
INSERT INTO ha_module (`name`, `class`, `tier`, `description`, `damage`, `frequency`, `damage_range`, `price`, `sell_price`) VALUES ('Bitcoin Miner', 'money', 2, 'Upgraded Bitcoin Miner (Tier 2)', 0, 50, 0, 5000, 0);
INSERT INTO ha_module (`name`, `class`, `tier`, `description`, `damage`, `frequency`, `damage_range`, `price`, `sell_price`) VALUES ('Bitcoin Miner', 'money', 3, 'Upgraded Bitcoin Miner (Tier 3)', 0, 100, 0, 12000,0);
INSERT INTO ha_module (`name`, `class`, `tier`, `description`, `damage`, `frequency`, `damage_range`, `price`, `sell_price`) VALUES ('Software Injector', 'base', 1, 'Default Software Injector', 0, 0, 0, 0, 0);
INSERT INTO ha_module (`name`, `class`, `tier`, `description`, `damage`, `frequency`, `damage_range`, `price`, `sell_price`) VALUES ('Software Injector', 'base', 2, 'Upgraded Software Injector (Tier 2)', 0, 0, 0, 0, 0);
INSERT INTO ha_module (`name`, `class`, `tier`, `description`, `damage`, `frequency`, `damage_range`, `price`, `sell_price`) VALUES ('Software Injector', 'base', 3, 'Upgraded Software Injector (Tier 3)', 0, 0 ,0 ,0 ,0);
INSERT INTO ha_module (`name`, `class`, `tier`, `description`, `damage`, `frequency`, `damage_range`, `price`, `sell_price`) VALUES ('CPU Upgrade', 'base', 1, 'Default CPU Upgrade', 0, 0, 0, 0, 0);
INSERT INTO ha_module (`name`, `class`, `tier`, `description`, `damage`, `frequency`, `damage_range`, `price`, `sell_price`) VALUES ('CPU Upgrade', 'base', 2, 'Upgraded CPU Upgrade (Tier 2)', 0, 0, 0, 0, 0);
INSERT INTO ha_module (`name`, `class`, `tier`, `description`, `damage`, `frequency`, `damage_range`, `price`, `sell_price`) VALUES ('CPU Upgrade', 'base', 3, 'Upgraded CPU Upgrade (Tier 3)', 0, 0, 0, 0, 0);
